USE [MDM]
GO

CREATE TABLE [dbo].[TEST1_MDM_ASIN](	[
	[ASINMasterId] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY,
    [ASIN][varchar](50) NULL,
	[ASIN_Name] [varchar](255) NULL,
	
	[StartDate] [datetime2](2) GENERATED ALWAYS AS ROW START NOT NULL,
	[EndDate] [datetime2](2) GENERATED ALWAYS AS ROW END NOT NULL,
	PERIOD FOR SYSTEM_TIME (StartDate, EndDate) 

) 
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.TEST1_HIST_ASIN));
