USE [MDM]
GO

CREATE TABLE [dbo].[TEST1_MDM_PRODUCT_LINK](	
    [ID] int NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[UPCMasterId] [int] NOT NULL,
	[UPC] [nvarchar](50) NULL,
	[UPCName] [nvarchar](255) NULL,	
	[ASINMasterId] [int] NULL,
    [ASIN][varchar](50) NULL,
	[ASIN_Name] [varchar](255) NULL,
	[StartDate] [datetime2](2) GENERATED ALWAYS AS ROW START NOT NULL,
	[EndDate] [datetime2](2) GENERATED ALWAYS AS ROW END NOT NULL,
	PERIOD FOR SYSTEM_TIME (StartDate, EndDate) 

) 
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.TEST1_HIST_PRODUCT_LINK));