create table dbo.TEST1_MDM_PRODUCT_LINK
(
	ID int IDENTITY(1,1) NOT NULL  PRIMARY KEY,
	[UPCMasterId] [int] NULL,
	[ASINMasterId] [int] NULL,		
	[StartDate] [datetime2](2) GENERATED ALWAYS AS ROW START NOT NULL,
	[EndDate] [datetime2](2) GENERATED ALWAYS AS ROW END NOT NULL,
	PERIOD FOR SYSTEM_TIME (StartDate, EndDate) 

) 
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.TEST1_HIST_PRODUCT_LINK));